# Generated by Django 2.2.1 on 2019-05-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_messageinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='广告图')),
                ('desc', models.CharField(max_length=20, verbose_name='广告描述')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.AlterModelOptions(
            name='messageinfo',
            options={'verbose_name': '信息', 'verbose_name_plural': '信息'},
        ),
    ]
