# Generated by Django 2.2.1 on 2019-05-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20190515_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
