# Generated by Django 2.2.1 on 2019-05-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_column='time', null=True),
        ),
    ]
