# Generated by Django 2.2.1 on 2019-05-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_temp_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='name',
            field=models.CharField(help_text='角色昵称', max_length=30, verbose_name='角色名'),
        ),
    ]
