# Generated by Django 2.2.1 on 2019-05-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_auto_20190517_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='account',
            new_name='acc',
        ),
    ]
