# Generated by Django 2.2.1 on 2019-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0010_application_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'testmodel1',
            },
        ),
    ]
