# Generated by Django 2.2.1 on 2019-05-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0011_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'ordering': ['-title']},
        ),
    ]
