# Generated by Django 2.2.1 on 2019-05-17 08:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0012_auto_20190517_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='testmodel',
            options={'ordering': ['-title'], 'verbose_name': '测试模型类', 'verbose_name_plural': '测试模型类'},
        ),
        migrations.AlterModelManagers(
            name='testmodel',
            managers=[
                ('manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
